//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityFrameworkDatabaseFirst
{
    using System;
    
    public enum CourseLevel : byte
    {
        Beginner = 0,
        Intermidiate = 1,
        Advanced = 2
    }
}
